#!/bin/sh

# Source system xinitrc files
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Set keyboard layout
setxkbmap us &

# Set display resolution
xrandr --output Virtual-1 --mode 1920x1080 &

# Start compositor
picom --config $HOME/.config/picom/picom.conf &

# Set wallpaper and generate colorscheme
wal -i "$(find $HOME/assets/wallpapers -type f | shuf -n 1)" &

# Start status bar script
$HOME/.config/dwm/autostart.sh &

# Start window manager
exec dwm
